### ISSUE TITLE
Issues to project action fails when creating new issue

### ISSUE THREAD

**Issue by Klyyssi** [Yleisradio/gh-project-actions#9]
# How to reproduce

## Prerequisite

Github repo with following action

```yml
name: Add new issue to Vuorovaikutustiimi project
on:
  issues:
    types:
      - opened
      - reopened

jobs:
  add_issue_to_project:
    name: 'Add issue to project board (new, reopened, labelled)'
    runs-on: ubuntu-latest
    steps:
      - uses: Yleisradio/gh-project-actions/issues-to-project@v1.1.0
        with:
          token: ${{secrets.GH_ACTIONS_TOKEN}}
          project-id: 17
          issue-id: ${{ github.event.issue.node_id }}
          target-column: Inbox
```

## Steps

1. Add new Issue in the repo

## Expectation

Issue is added to github board

## Actual

Action fails with error

```
Run $GITHUB_ACTION_PATH/issues_to_project.sh
- Get project and field data
gh: Field 'projectNext' doesn't exist on type 'Organization'
Variable $number is declared by anonymous query but not used
jq: error (at project_data.json:0): Cannot iterate over null (null)
- Looking for issue I_kwDOA_uAiM5eUjuu in project null
gh: No such type ProjectNext, so it can't be a fragment condition
Variable $endCursor is declared by anonymous query but not used
jq: error (at board_issues.json:0): Cannot iterate over null (null)
- Issue not found in project
- Add Issue to the project board
gh: Field 'addProjectNextItem' doesn't exist on type 'Mutation'
Variable $project_id is declared by anonymous mutation but not used
Variable $content_id is declared by anonymous mutation but not used
- New board item id is {"errors":[{"path":["mutation","addProjectNextItem"],"extensions":{"code":"undefinedField","typeName":"Mutation","fieldName":"addProjectNextItem"},"locations":[{"line":3,"column":9}],"message":"Field 'addProjectNextItem' doesn't exist on type 'Mutation'"},{"path":["mutation"],"extensions":{"code":"variableNotUsed","variableName":"project_id"},"locations":[{"line":2,"column":7}],"message":"Variable $project_id is declared by anonymous mutation but not used"},{"path":["mutation"],"extensions":{"code":"variableNotUsed","variableName":"content_id"},"locations":[{"line":2,"column":7}],"message":"Variable $content_id is declared by anonymous mutation but not used"}]}.
```

## Example

https://github.com/Yleisradio/tehtava-ui/actions/runs/4164423336/jobs/7206039181

**Comment by rpsu** [comment]
Are you sure the `GH_ACTIONS_TOKEN` token is set? the regular token does not have permission to query project data
@see https://github.com/Yleisradio/gh-project-actions/blob/main/issues-to-project/action.yml#L8-L10

**Comment by Klyyssi** [comment]
Thanks @rpsu for the idea. I checked project settings, and I can see `GH_ACTIONS_TOKEN` organization secret is set and was updated last November. 

There is also `ACTIONS_TOKEN` organization secret which was updated last December, which makes me think should we be using it instead :thinking:

**Comment by rpsu** [comment]
oh well, some data structure has changed, [CI fails here as well](https://github.com/Yleisradio/tag-mapper/actions/runs/4171768056/jobs/7222064291).

**Comment by rpsu** [comment]
https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/automating-projects-using-actions has been updated at some point. Until this change is implemented here the action is broken.

**Comment by hugovk** [comment]
We're using GitHub's fairly new https://github.com/actions/add-to-project directly to add _pull requests_ to a project:

```
name: Add PR to project
on:
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/orgs/Yleisradio/projects/25
          github-token: ${{ secrets.GH_ACTIONS_TOKEN }}
```

https://github.com/Yleisradio/yddrasil/blob/f89c9582507ac2326ad91455e62c22ed0b8f1478/.github/workflows/add-pr-to-project.yml

Sample runs:

https://github.com/Yleisradio/yddrasil/actions/workflows/add-pr-to-project.yml

Example PR added to project: https://github.com/Yleisradio/yddrasil/pull/6816

---

The actions's README specifically says it doesn't use projectNext, which causes the problems above:

> NOTE: ⚠️ This action no longer uses the deprecated ProjectNext API. If you are looking for the old version of that action, use version [v0.0.5](https://github.com/actions/add-to-project/releases/tag/v0.0.5).
